### ISSUE TITLE
logout url is invalid

### ISSUE THREAD

**Issue by Panmax** [kakawait/cas-security-spring-boot-starter#10]
when i visit my application's `/logout` url, it raise 404 error.

![image](https://user-images.githubusercontent.com/3353761/27567565-2d547154-5b1f-11e7-9714-aca08f01c8ae.png)

this is the configuration：

```
server:
  port: 8081

security:
  cas:
    server:
      base-url: http://127.0.0.1:8080/cas/
    service:
      resolution-mode: dynamic
  ignored: /ignored
```

BTW. **dynamic** resolution mode is OK.
