### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Pattern cannot be null or empty

### ISSUE THREAD

**Issue by Tyvain** [kakawait/cas-security-spring-boot-starter#110]
I want to protect every resources in /secured/* but I get this error:
"Pattern cannot be null or empty"

with /** it works, but even my public resources (css, html...) are protected

```yml
security:
  cas:
    paths: /secured/
    server:
      base-url: https://myserver/cas
    service:
      base-url: http://localhost:8080/secured
```
