### ISSUE TITLE
Using rest api error.

### ISSUE THREAD

**Issue by coskundeniz89** [kakawait/cas-security-spring-boot-starter#14]
Hi. Thank you for this project. It is best for cas auto config. But i have a little problem. 

I did a cas-client project with gradle and it looks like good. My application.yml is that:
```yml
security:
  basic:
    enabled: false
  ignored: /
  cas:
    paths: /protected
    server:
      base-url: https://localhost:10100/cas
      protocol-version: 2
    service:
      base-url: https://localhost:8443
      paths:
        proxy-callback: /j_spring_cas_security_proxyreceptor

server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:/etc/keystore/localhost.jks
    key-store-password: changeit
```
Cas server runs on 10100 port. The client web project works good. But i want to access controller to through get and post method. 

I try that: (i use postman)

1. step :
```
Header:
POST https://localhost:10100/cas/v1/tickets
Content-Type: application/x-www-form-urlencoded
Body:
username=myname&password=123456
```
1. step result:
Body (html format):
```html
<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">
<html>
    <head>
        <title>201 Created</title>
    </head>
    <body>
        <h1>TGT Created</h1>
        <form action="https://localhost:10100/cas/v1/tickets/TGT-32-NfRV2HIYL6JlqUFTpJuc6EfUyH6q9BImaS0a5CPyOpInrO3fqk-8ee6f154afba" method="POST">Service:
            <input type="text" name="service" value="">
            <br>
            <input type="submit" value="Submit">
        </form>
    </body>
</html>
```

2. step:
I want to get a service ticket for "https://localhost:8443/protected"
```
Header:
POST https://localhost:10100/cas/v1/tickets/TGT-32-NfRV2HIYL6JlqUFTpJuc6EfUyH6q9BImaS0a5CPyOpInrO3fqk-8ee6f154afba
Content-Type: application/x-www-form-urlencoded
Body:
service=https%3A%2F%2Flocalhost%3A8443%2Fprotected
```
2. step result:
```text
ST-171-b2Sz3TseQlmFjthK7xqV-8ee6f154afba
```

3. step:
```
Header:
GET https://localhost:8443/protected?ticket=ST-171-b2Sz3TseQlmFjthK7xqV-8ee6f154afba
```

I expect my protected page html format. But i saw login page. What is the problem? Could you help me?
