### ISSUE TITLE
i got status=401 when i use resolution-mode: dynamic

### ISSUE THREAD

**Issue by Panmax** [kakawait/cas-security-spring-boot-starter#3]
![image](https://user-images.githubusercontent.com/3353761/27473690-93452778-5832-11e7-9e8e-1eb536fc9638.png)

but static mode is ok.

**Comment by kakawait** [comment]
@Panmax Thank you for feedback, can you please share with me your configuration file?

**Comment by Panmax** [comment]
this is my config file:

```
server:
  port: 8081

security:
  cas:
    server:
      base-url: http://127.0.0.1:8080/cas/
    service:
      resolution-mode: dynamic
  ignored: /ignored
```

and there is no error log in terminal.

**Comment by kakawait** [comment]
In fact it's more an issue with `static` mode which does not compute URL correctly 

```
http://localhost:8781/cas/p3/proxyValidate?pgtUrl=%2Fcas%2Fproxy-callback&ticket=ST-12-jcxNnklCEm3bIEIdjbb7-6caae9445ce0&service=http%3A%2F%2F127.0.0.1%3A8080%2Flogin
```

Check `pgtUrl` parameter is not a valid url, thus is _disabling_ pgt callback.

I think when fixed you will have same problem with `static` and `dynamic`.

---

Does your CAS server is able to contact your service, during PGT callback process?

**Comment by kakawait** [comment]
@Panmax When `0.1.2` will be released can you please upgrade your configuration like following:

```yml
server:
  port: 8081

security:
  cas:
    server:
      base-url: http://127.0.0.1:8080/cas/
    service:
      proxy-callback-enabled: false
      resolution-mode: dynamic
  ignored: /ignored
```

**Comment by Panmax** [comment]
ok, i will try. thank you.

**Comment by kakawait** [comment]
I will release it in 5min (+ time to maven central to be fresh)

**Comment by Panmax** [comment]
i am a CAS new user, i don't know what's PGT callback process.

**Comment by Panmax** [comment]
My CAS config :

```
server.context-path=/cas

cas.server.port=
cas.server.http.port=8080
cas.server.name: http://127.0.0.1:8080
cas.server.prefix: http://127.0.0.1:8080/cas

cas.adminPagesSecurity.ip=127\.0\.0\.1

logging.config: file:/etc/cas/config/log4j2.xml
# cas.serviceRegistry.config.location: classpath:/services

cas.authn.accept.users=
server.ssl.enabled=false
cas.tgc.secure=false
cas.warningCookie.secure=false
cas.logout.followServiceRedirects=true

cas.authn.jdbc.query[0].sql=select password from account where username=?
cas.authn.jdbc.query[0].healthQuery=SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
cas.authn.jdbc.query[0].isolateInternalQueries=false
cas.authn.jdbc.query[0].url=jdbc:mysql://localhost:3306/jupiter?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
cas.authn.jdbc.query[0].failFast=true
cas.authn.jdbc.query[0].isolationLevelName=ISOLATION_READ_COMMITTED
cas.authn.jdbc.query[0].dialect=org.hibernate.dialect.MySQL56InnoDBDialect
cas.authn.jdbc.query[0].leakThreshold=10
cas.authn.jdbc.query[0].propagationBehaviorName=PROPAGATION_REQUIRED
cas.authn.jdbc.query[0].batchSize=1
cas.authn.jdbc.query[0].user=root
cas.authn.jdbc.query[0].ddlAuto=update
cas.authn.jdbc.query[0].maxAgeDays=180
cas.authn.jdbc.query[0].password=
cas.authn.jdbc.query[0].autocommit=false
cas.authn.jdbc.query[0].driverClass=com.mysql.jdbc.Driver
cas.authn.jdbc.query[0].idleTimeout=500

cas.authn.jdbc.query[0].passwordEncoder.type=DEFAULT
cas.authn.jdbc.query[0].passwordEncoder.encodingAlgorithm=MD5
```

**Comment by kakawait** [comment]
@Panmax Unfortunately I'm most a CAS client user than CAS server power user so I can't help you with CAS server configuration.

About _proxy callback_ you may find some useful information here https://wiki.jasig.org/display/CAS/Proxy+CAS+Walkthrough

But to summaries, when client validate the ticket using `/serviceValidate` or `/proxyValidate` API if you add `pgtUrl` as parameter (see [specification](https://github.com/apereo/cas/blob/96472e325cc323fa5baede95fc3447a5b9827f2f/docs/cas-server-documentation/protocol/CAS-Protocol-Specification.md#251-parameters)) then CAS server will contact your server (is new request, CAS server will use its own _http client_) to send you `PGT` _proxy granting ticket_ ticket (ticket that in mandatory to ask `PT` _proxy ticket_ ticket). **But** if CAS server is not able to contact your server (network issue, DNS issue, etc?) it will break the flow.

**Comment by Panmax** [comment]
i understood, thank you very much.

**Comment by kakawait** [comment]
@Panmax After more thinking I will change configuration, I will delete `proxy-callback-enabled` property instead I will do other way. I will keep you in touch

**Comment by Panmax** [comment]
👌🏻

**Comment by Panmax** [comment]
i upgrade to 0.1.2 but when i visit my site, it doesn't redirect to CAS login page, but shows Hello anonymous.

**Comment by kakawait** [comment]
Artifact is not yet upload. I think maven simply just not find the artifact that has disable starter since maven can't fetch it

**Comment by Panmax** [comment]
alright😂

**Comment by kakawait** [comment]
@Panmax with this new `PR` you will no need to change your initial configuration, so please keep

```yml
server:
  port: 8081

security:
  cas:
    server:
      base-url: http://127.0.0.1:8080/cas/
    service:
      resolution-mode: dynamic
  ignored: /ignored
```
