### ISSUE TITLE
Automatically add `login-path` path inside path to be handle by cas filter

### ISSUE THREAD

**Issue by kakawait** [kakawait/cas-security-spring-boot-starter#57]
With following conf:

```
security:
  basic:
    enabled: false
  ignored: /ignored, /**/favicon.ico
  cas:
    server:
      base-url: http://localhost:8080/cas/
      protocol-version: 3
    service:
      resolution-mode: dynamic
    paths: /test
```

Auth does not work anymore because `/login` is not treated by _CAS filters_

**Workaroud**

```
security:
  basic:
    enabled: false
  ignored: /ignored, /**/favicon.ico
  cas:
    server:
      base-url: http://localhost:8080/cas/
      protocol-version: 3
    service:
      resolution-mode: dynamic
    paths: /test, /login
```
